Fixes for multiple issues. Add logging with timestamps.

diff --git a/BackupRestore/columnstoreBackup b/BackupRestore/columnstoreBackup
--- a/BackupRestore/columnstoreBackup
+++ b/BackupRestore/columnstoreBackup
@@ -9,17 +9,62 @@ BACKUP_SERVER_LOCATION=none
 DRY_RUN=false
 REMOTE_USER=root
 NUMBER_BACKUPS=3
+LOG_FILE=$0.log
+
+exec 3>&1 1>${LOG_FILE} 2>&1
+
+startTime=`date +%s`
+
+printLog () {
+    LOGTIME="[`date "+%Y-%m-%d %H:%M:%S"`] "
+    echo $LOGTIME$* | tee /dev/fd/3
+}
+
+verbosePrint () {
+    if [ "$VERBOSE" = true ]; then
+        printLog $*
+    fi
+}
+
+##
+## ERROR CODES
+##
+## 1   - command line parameter or config file issue detected
+## 2   - missing rsync or xmllint
+## 3   - detected issue with disk space
+## 4   - detected bad configuration file settings
+## 5   - rsync command failed with an error
+## 255 - could not connect via passwordless ssh
+
+reportStatus () {
+    if [ $1 != 0 ]; then
+        printLog "Backup Status: Failed"
+    else
+        printLog "Backup Status: Success"
+    fi
+    endTime=`date +%s`
+    runtime=$(( $endTime - $startTime ))
+    runtimeHours=$(( $runtime / 3600 ))
+    runtimeMinutes=$(( $(( $runtime % 3600 )) / 60 ))
+    runtimeSeconds=$(( $runtime % 60 ))
+    line=$(printf "%02d:%02d:%02d" $runtimeHours $runtimeMinutes $runtimeSeconds)
+    printLog Runtime: $line
+    exit $1
+}
+
+printLog "[$USER] $0 $@"
 
 if [ -e columnstoreBackup.config ]; then
     source columnstoreBackup.config
 fi
 REcheck='^[0-9]+$'
 if ! [[ $NUMBER_BACKUPS =~ $REcheck ]] ; then
-   echo "ERROR: NUMBER_BACKUPS not a number" >&2; exit 1
+   printLog "ERROR: NUMBER_BACKUPS not a number" >&2
+   reportStatus 1
 fi
 if [ $NUMBER_BACKUPS -lt 0 ] || [ $NUMBER_BACKUPS -gt 20 ]; then
-    echo "ERROR: NUMBER_BACKUPS must be an integer between 1 and 100 (value: $NUMBER_BACKUPS)" >&2
-    exit 1
+    printLog "ERROR: NUMBER_BACKUPS must be an integer between 1 and 100 (value: $NUMBER_BACKUPS)" >&2
+    reportStatus 1
 fi
 
 ###
@@ -52,10 +97,10 @@ helpPrint () {
     echo "The impact on extra space needed is based on the amount data that changes."
     echo "with little to no data set changes the incremental backup size is small."
     echo ""
-    echo "Usage: $0 [options] pm1 backupServerLocation"
+    echo "Usage: $0 [options] activeParentOAM backupServerLocation"
     echo ""
-    echo "pm1                       IP address of ColumnStore server"
-    echo "                              (PM1 if Multi-Node install)"
+    echo "activeParentOAM           IP address of ColumnStore server"
+    echo "                             (Active parent OAM module on multi-node install)"
     echo "backupServerLocation      Path to the directory for storing backup files."
     echo ""    
     echo "OPTIONS:"
@@ -70,19 +115,11 @@ helpPrint () {
     echo ""
 }
 
-verbosePrint () {
-    if [ "$VERBOSE" = true ]; then
-        echo $1 
-    fi
-}
-
-
-
 # Parse command line options.
 while getopts hdzv-: OPT; do
     case "$OPT" in
         h)
-            echo $USAGE
+            printLog $USAGE
             helpPrint
             exit 0
             ;;
@@ -118,41 +155,41 @@ while getopts hdzv-: OPT; do
                     REMOTE_USER="$LONG_OPTARG" 
                     ;;                    
                 install-dir* )  
-                    echo "No arg for --$OPTARG option" >&2
-                    exit 1
+                    printLog "No arg for --$OPTARG option" >&2
+                    reportStatus 1
                     ;;
                 user* )  
-                    echo "No arg for --$OPTARG option" >&2
-                    exit 1
+                    printLog "No arg for --$OPTARG option" >&2
+                    reportStatus 1
                     ;;
                 help* )  
                     helpPrint
                     exit 0
                     ;;                                        
                 compress* )
-                    echo "No arg allowed for --$OPTARG option" >&2
-                    exit 1 
+                    printLog "No arg allowed for --$OPTARG option" >&2
+                    reportStatus 1 
                     ;;
                 dry-run* )
-                    echo "No arg allowed for --$OPTARG option" >&2
-                    exit 1
+                    printLog "No arg allowed for --$OPTARG option" >&2
+                    reportStatus 1
                     ;;      
                 verbose* )
-                    echo "No arg allowed for --$OPTARG option" >&2
-                    exit 1
+                    printLog "No arg allowed for --$OPTARG option" >&2
+                    reportStatus 1
                     ;;                    
                 '' )
                     break ;; # "--" terminates argument processing
                 * )
-                    echo "Illegal option --$OPTARG" >&2
-                    exit 1
+                    printLog "Illegal option --$OPTARG" >&2
+                    reportStatus 1
                     ;;
             esac 
             ;;       
         \?)
             # getopts issues an error message
-            echo $USAGE >&2
-            exit 1
+            printLog $USAGE >&2
+            reportStatus 1
             ;;
     esac
 done
@@ -163,29 +200,29 @@ shift `expr $OPTIND - 1`
 # We want 2 non-option argument. 
 if [ $# -ne 2 ]; then
     if [ $# -lt 2 ]; then
-        echo "Missing arguments." >&2
+        printLog "Missing arguments." >&2
     fi
     if [ $# -gt 2 ]; then
-        echo "Unknown extra arguments." >&2
+        printLog "Unknown extra arguments." >&2
     fi
-    echo $USAGE >&2
-    exit 1
+    printLog $USAGE >&2
+    reportStatus 1
 fi
 
 ## Check if root or sudo
 if [[ $EUID -ne 0 ]]; then
-   echo "ERROR: This script must be run as root or with sudo" 
-   exit 1
+   printLog "ERROR: This script must be run as root or with sudo" 
+   reportStatus 1
 fi
 
 ## Check rsync and xmllint are available
 if ! type rsync > /dev/null; then
-    echo "rsync is not installed. Please install and rerun." >&2
-    exit 2
+    printLog "rsync is not installed. Please install and rerun." >&2
+    reportStatus 2
 fi
 if ! type xmllint > /dev/null; then
-    echo "xmllint is not installed. Please install and rerun." >&2
-    exit 2
+    printLog "xmllint is not installed. Please install and rerun." >&2
+    reportStatus 2
 fi
 
 #
@@ -207,9 +244,9 @@ fi
 rsyncCommand="$rsyncCommand$rsyncOptions$rsyncLongOptions"
 
 if ! ssh -q -o "BatchMode yes" $REMOTE_USER@$PM1 ls $INSTALL_DIR > /dev/null; then
-    echo "ERROR: Cannot connect to $REMOTE_USER@$PM1" >&2
-    echo "Check that ssh and passwordless login are available." >&2
-    exit 255
+    printLog "ERROR: Cannot connect to $REMOTE_USER@$PM1" >&2
+    printLog "Check that ssh and passwordless login are available." >&2
+    reportStatus 255
 fi
 
 ## EX ARG pm1dbroot1
@@ -261,12 +298,12 @@ command="$rsyncCommand $extraOptions $source $dest"
 if [ "$dryRunFlag" = false ]; then
     verbosePrint "$command"
     if ! $command; then
-        echo "ERROR: Rsync command failed." >&2
-        echo "ERROR Command: $command" >&2
-        exit 4
+        printLog "ERROR: Rsync command failed." >&2
+        printLog "ERROR Command: $command" >&2
+        reportStatus 5
     fi
 else
-    echo "$command"
+    printLog "$command"
     $command    
 fi
 }
@@ -289,7 +326,7 @@ if [ "$dryRunFlag" = false ]; then
     verbosePrint "$command"
     { $command ; echo "$?" > "$resultsDir" ; } &
 else
-    echo "$command"
+    printLog "$command"
     $command
 fi
 }
@@ -298,15 +335,15 @@ waitRsyncBackground () {
 dataSize=$1
 dir=$2
 if [ "$DRY_RUN" = false ]; then
-    echo "Waiting for backups to complete..."
+    printLog "Waiting for backups to complete..."
     monitorProgress $dataSize $dataLocation
     wait
     for file in "$dir"/*; do
         if [ $(<"$file") != 0 ]; then
-            echo "ERROR: RSYNC failed $file with Error: $(<"$file")" >&2
-            echo "Backup may not be usable." >&2
+            printLog "ERROR: RSYNC failed $file with Error: $(<"$file")" >&2
+            printLog "Backup may not be usable." >&2
             rm -r "$dir"                       
-            exit 6
+            reportStatus 5
         fi
     done
 fi
@@ -354,9 +391,9 @@ if [ $singleServerInstall == "n" ]; then
             umModuleIP[$moduleID]=$umModuleIP2
             umModuleHostname[$moduleID]=$umModuleHostname2
         else
-            echo "ERROR: cannot Connect to UM$moduleID" >&2
-            echo "(IP1 = $umModuleIP1)" >&2
-            echo "(IP2 = $umModuleIP2)" >&2
+            printLog "ERROR: cannot Connect to UM$moduleID" >&2
+            printLog "(IP1 = $umModuleIP1)" >&2
+            printLog "(IP2 = $umModuleIP2)" >&2
             detectError=true
         fi
     done
@@ -375,9 +412,9 @@ if [ $singleServerInstall == "n" ]; then
             pmModuleIP[$moduleID]=$pmModuleIP2
             pmModuleHostname[$moduleID]=$pmModuleHostname2
         else
-            echo "ERROR: Cannot connect to PM$moduleID" >&2
-            echo "(IP1 = $pmModuleIP1)" >&2
-            echo "(IP2 = $pmModuleIP2)" >&2
+            printLog "ERROR: Cannot connect to PM$moduleID" >&2
+            printLog "(IP1 = $pmModuleIP1)" >&2
+            printLog "(IP2 = $pmModuleIP2)" >&2
             detectError=true
         fi
         
@@ -393,8 +430,8 @@ if [ $singleServerInstall == "n" ]; then
         done
     fi
     if [ "$detectError" = true ]; then
-        echo "Check that ssh and passwordless login are available." >&2
-        exit 255 
+        printLog "Check that ssh and passwordless login are available." >&2
+        reportStatus 255 
     fi
     
 elif [ $singleServerInstall == "y" ]; then
@@ -408,8 +445,8 @@ elif [ $singleServerInstall == "y" ]; then
     pmModuleIP[1]=$PM1
        
 else
-    echo "Unknown install type = $installType" >&2
-    exit 2
+    printLog "Unknown install type = $installType" >&2
+    reportStatus 4
 fi
 
 }
@@ -428,8 +465,21 @@ measureDiskSpace () {
                 totalDiskSpaceNeeded=$(( $totalDiskSpaceNeeded + ${returnValues[0]} ))
                 totalDiskSpaceNeededPM=$(( $totalDiskSpaceNeededPM + ${returnValues[0]} ))                
             else
-                echo "failed return from command: $command" >&2
-                exit 2
+                printLog "failed return from command: $command" >&2
+                reportStatus 3
+            fi
+            if [ $PMwithUM == "yes" ]; then
+                command="ssh $REMOTE_USER@${pmModuleIP[$moduleID]} du -s -b $INSTALL_DIR/mysql/db"
+                verbosePrint "$command"
+                commandReturn=$($command)
+                returnValues=($commandReturn)
+                if [ ${returnValues[1]} == $INSTALL_DIR/mysql/db ]; then
+                    totalDiskSpaceNeeded=$(( $totalDiskSpaceNeeded + ${returnValues[0]} ))
+                    totalDiskSpaceNeededPM=$(( $totalDiskSpaceNeededPM + ${returnValues[0]} ))                
+                else
+                    printLog "failed return from command: $command" >&2
+                    reportStatus 3
+                fi                
             fi
         done        
     done
@@ -442,8 +492,8 @@ measureDiskSpace () {
             totalDiskSpaceNeeded=$(( $totalDiskSpaceNeeded + ${returnValues[0]} ))
             totalDiskSpaceNeededUM=${returnValues[0]}               
         else
-            echo "failed return from command: $command" >&2
-            exit 2
+            printLog "failed return from command: $command" >&2
+            reportStatus 3
         fi
     done
     totalDiskSpaceAvailable=$(df -B1 $BACKUP_SERVER_LOCATION | awk 'NR==2 {print $4}')
@@ -539,7 +589,7 @@ do
     
     bar=$bar"] ($percentDone%) $rate "
     line=$(printf "%02d:%02d:%02d %s" $printHours $printMinutes $printSeconds "Approx Time Remaining          ")
-    echo -en "${bar}${line}\r"
+    echo -en "${bar}${line}\r" 1>&3
     if [ $stallCount -gt 5 ]; then
         rsyncStalled=true;
         break
@@ -552,7 +602,7 @@ if [ $rsyncStalled == false ]; then
     percentDone=100
     bar="Progress [=========================>] ($percentDone%) $rate "
     line=$(printf "%02d:%02d:%02d %s" $printHours $printMinutes $printSeconds "Approx Time Remaining          ")
-    echo -en "${bar}${line}\n"
+    echo -en "${bar}${line}\n" 1>&3
 fi
 }
 
@@ -560,7 +610,7 @@ fi
 # Backup PM
 ###############################################################################
 backupPMs () {
-echo "Backing up PMs"
+printLog "Backing up PMs"
 dir=$(mktemp -d)
 ## loop the pmModules
 for (( moduleID=1; moduleID<=$pmModuleCount; moduleID++ ))
@@ -572,23 +622,32 @@ do
         if [ ! -e $BACKUP_SERVER_LOCATION/$pmBackupDir ]; then
             mkdir $BACKUP_SERVER_LOCATION/$pmBackupDir
         fi
-        echo "Backing up $pmBackupDir"
+        printLog "Backing up $pmBackupDir"
         moveBackupFiles $pmBackupDir ./backup.1/
         # Launch it in background
-        executeRsyncBackground $DRY_RUN /$dir/$pmBackupDir --link-dest=../backup.1/$pmBackupDir $REMOTE_USER@${pmModuleIP[$moduleID]}:${DBRoot[$thisDBrootID]} $BACKUP_SERVER_LOCATION/$pmBackupDir
+        executeRsyncBackground $DRY_RUN /$dir/$pmBackupDir "--copy-links --link-dest=../backup.1/$pmBackupDir" $REMOTE_USER@${pmModuleIP[$moduleID]}:${DBRoot[$thisDBrootID]} $BACKUP_SERVER_LOCATION/$pmBackupDir
+        
+        if [ $PMwithUM == "yes" ]; then
+            pmBackupDirDB="pm"$moduleID"DB"
+            printLog "Backing up $pmBackupDir local query data"
+            if [ ! -e $BACKUP_SERVER_LOCATION/$pmBackupDirDB ]; then
+                mkdir $BACKUP_SERVER_LOCATION/$pmBackupDirDB
+            fi
+            executeRsync $DRY_RUN --link-dest=../backup.1/$pmBackupDirDB $REMOTE_USER@${pmModuleIP[$moduleID]}:$INSTALL_DIR/mysql/db $BACKUP_SERVER_LOCATION/$pmBackupDirDB           
+        fi
     done        
 done
 
 waitRsyncBackground $totalDiskSpaceNeededPM $dir
 rm -rf "$dir"
-echo -e "\nDONE"
+printLog "DONE"
 }
 
 ###############################################################################
 # Backup UM
 ###############################################################################
 backupUM () {
-echo "Backing up UM"
+printLog "Backing up UM"
 ## dir=$(mktemp -d)
 ## loop the pmModules
 for (( moduleID=1; moduleID<=$umModuleCount; moduleID++ ))
@@ -598,14 +657,14 @@ do
         mkdir $BACKUP_SERVER_LOCATION/$umBackupDir
     fi
     
-    echo "Backing up $umBackupDir"
+    printLog "Backing up $umBackupDir"
     moveBackupFiles $umBackupDir ./backup.1/
     # Launch it in background
     executeRsync $DRY_RUN --link-dest=../backup.1/$umBackupDir $REMOTE_USER@${umModuleIP[$moduleID]}:$INSTALL_DIR/mysql/db $BACKUP_SERVER_LOCATION/$umBackupDir
 done
 
 #waitRsyncBackground $totalDiskSpaceNeededUM $dir
-echo -e "\nDONE"
+printLog "DONE"
 }
 
 
@@ -629,7 +688,7 @@ if [ "$DRY_RUN" = false ]; then
     if [ "$VERBOSE" = true ]; then
         ssh $REMOTE_USER@$PM1 $INSTALL_DIR/bin/mcsadmin suspendDatabaseWrites y
     else
-        echo "Suspend DB Writes"
+        printLog "Suspend DB Writes"
         ssh $REMOTE_USER@$PM1 $INSTALL_DIR/bin/mcsadmin suspendDatabaseWrites y > /dev/null
     fi
 fi
@@ -644,7 +703,7 @@ if [ "$DRY_RUN" = false ]; then
     if [ "$VERBOSE" = true ]; then
         ssh $REMOTE_USER@$PM1 $INSTALL_DIR/bin/mcsadmin resumeDatabaseWrites y
     else
-        echo "Resume DB Writes"
+        printLog "Resume DB Writes"
         ssh $REMOTE_USER@$PM1 $INSTALL_DIR/bin/mcsadmin resumeDatabaseWrites y > /dev/null
     fi
 fi    
@@ -708,10 +767,10 @@ measureDiskSpace
 #verbosePrint "totalDiskSpaceAvailable:   $totalDiskSpaceAvailable"
 
 if (( $totalDiskSpaceAvailable < $totalDiskSpaceNeeded )); then
-    echo "ERROR: Not enough space on backup system" >&2
-    echo "(Needs = $totalDiskSpaceNeeded)" >&2
-    echo "(Avail = $totalDiskSpaceAvailable)" >&2
-    exit 3
+    printLog "ERROR: Not enough space on backup system" >&2
+    printLog "(Needs = $totalDiskSpaceNeeded)" >&2
+    printLog "(Avail = $totalDiskSpaceAvailable)" >&2
+    reportStatus 3
 fi
 
 ## suspend db writes
@@ -726,7 +785,7 @@ backupUM
 ## resume db writes
 resumeDBWrites
 
-exit 0
+reportStatus 0
 }
 
 ###############################################################################
@@ -734,5 +793,5 @@ exit 0
 ###############################################################################
 main
 
-exit 0
+reportStatus 0
 
